[versions]
gradle-starter = "0.53.0"
gradle-easylauncher = "5.1.2"
gradle-gradledoctor = "0.8.1"
gradle-karumi = "5.14.1"
gradle-animationdisabler = "1.0.9"
gradle-keeper = "0.12.0"
gradle-kotlinter = "3.12.0"
google-lifecycle = "2.5.1"
google-appcompat = "1.5.1"
google-swiperefreshlayout = "1.1.0"
google-recyclerView = "1.2.1"
google-constraintlayout = "2.1.4"
google-androidtest = "1.5.1"
google-androidtestext = "1.1.4"
google-androidArchCore = "2.1.0"
google-material = "1.7.0"
google-work = "2.7.1"
google-preference = "1.2.0"
google-paging = "3.1.1"
google-browser = "1.4.0"
google-viewpager2 = "1.0.0"
google-androidxcore = "1.9.0"
google-activity = "1.6.1"
google-fragment = "1.5.4"
google-datastore = "1.0.0"
google-cardview = "1.0.0"
google-exifinterface = "1.3.5"
google-startup = "1.1.1"
google-exoplayer = "2.18.1"
google-espresso = "3.5.0"
google-annotation = "1.5.0"
google-play-services = "4.3.14"
google-crashlytics = "2.9.2"
google-performance = "1.4.2"
google-tools = "30.3.1"
mavencentral-coroutines = "1.6.4"
mavencentral-okhttp = "4.10.0"
mavencentral-dagger = "2.44"
mavencentral-glide = "4.14.2"
mavencentral-shimmer = "0.5.0"
mavencentral-datetime = "0.4.0"
mavencentral-store = "4.0.5"
mavencentral-retrofit = "2.9.0"
mavencentral-moshi = "1.14.0"
mavencentral-sqldelight = "1.5.4"
mavencentral-jspoon = "1.3.2"
mavencentral-jsoup = "1.15.3"
mavencentral-slidr = "3.0.0"
mavencentral-leakcanary = "2.7"
mavencentral-markdown = "0.2.4"
mavencentral-junit = "5.9.1"
mavencentral-napier = "2.2.0"
mavencentral-checker = "3.21.2"
mavencentral-kotlin = "1.7.21"
jitpack-photoview = "2.3.0"
jitpack-subsampling-scale-image-view = "3.10.0"

[libraries]
appcompat-core = { module = "androidx.appcompat:appcompat", version.ref = "google-appcompat" }
constraintlayout-core = { module = "androidx.constraintlayout:constraintlayout", version.ref = "google-constraintlayout" }
material-core = { module = "com.google.android.material:material", version.ref = "google-material" }
swiperefreshlayout-core = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "google-swiperefreshlayout" }
recyclerview-core = { module = "androidx.recyclerview:recyclerview", version.ref = "google-recyclerView" }
preference-core = { module = "androidx.preference:preference-ktx", version.ref = "google-preference" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "google-work" }
work-testing = { module = "androidx.work:work-testing", version.ref = "google-work" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "mavencentral-okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mavencentral-okhttp" }
browser-core = { module = "androidx.browser:browser", version.ref = "google-browser" }
shimmer-core = { module = "com.facebook.shimmer:shimmer", version.ref = "mavencentral-shimmer" }
viewpager2-core = { module = "androidx.viewpager2:viewpager2", version.ref = "google-viewpager2" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "google-androidxcore" }
activity-core = { module = "androidx.activity:activity-ktx", version.ref = "google-activity" }
fragment-core = { module = "androidx.fragment:fragment-ktx", version.ref = "google-fragment" }
cardview-core = { module = "androidx.cardview:cardview", version.ref = "google-cardview" }
annotation-core = { module = "androidx.annotation:annotation", version.ref = "google-annotation" }
exifinterface-core = { module = "androidx.exifinterface:exifinterface", version.ref = "google-exifinterface" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "google-startup" }
store-core = { module = "com.dropbox.mobile.store:store4", version.ref = "mavencentral-store" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "google-datastore" }
jsoup-core = { module = "org.jsoup:jsoup", version.ref = "mavencentral-jsoup" }
usefulness-slidr = { module = "com.github.usefulness:slidr", version.ref = "mavencentral-slidr" }
chrisbanes-photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "jitpack-photoview" }
davemorrissey-subsamplingimageview = { module = "com.davemorrissey.labs:subsampling-scale-image-view-androidx", version.ref = "jitpack-subsampling-scale-image-view" }
leakcanary-core = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "mavencentral.leakcanary" }
jetbrains-markdown = { module = "org.jetbrains:markdown", version.ref = "mavencentral.markdown" }
napier-core = { module = "io.github.aakira:napier", version.ref = "mavencentral.napier" }

exoplayer-core = { module = "com.google.android.exoplayer:exoplayer", version.ref = "google-exoplayer" }
exoplayer-okhttp = { module = "com.google.android.exoplayer:extension-okhttp", version.ref = "google-exoplayer" }

lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "google-lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "google-lifecycle" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "google-lifecycle" }

paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "google-paging" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "google-paging" }

dagger-core = { module = "com.google.dagger:dagger", version.ref = "mavencentral-dagger" }
dagger-android = { module = "com.google.dagger:dagger-android-support", version.ref = "mavencentral-dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "mavencentral-dagger" }
dagger-compiler-android = { module = "com.google.dagger:dagger-android-processor", version.ref = "mavencentral-dagger" }

moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "mavencentral-moshi" }
moshi-compiler = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "mavencentral-moshi" }

sqldelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "mavencentral-sqldelight" }
sqldelight-extensions = { module = "com.squareup.sqldelight:coroutines-extensions-jvm", version.ref = "mavencentral-sqldelight" }
sqldelight-gradle = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "mavencentral-sqldelight" }

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "mavencentral-retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "mavencentral-retrofit" }
retrofit-converter-jspoon = { module = "pl.droidsonroids.retrofit2:converter-jspoon", version.ref = "mavencentral-jspoon" }

glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "mavencentral-glide" }
glide-okhttp = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "mavencentral-glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "mavencentral-glide" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "mavencentral-coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "mavencentral-coroutines" }
coroutines-rxjava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "mavencentral-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "mavencentral-datetime" }

starter-android-gradle = { module = "com.project.starter:android", version.ref = "gradle-starter" }
play-services-gradle = { module = "com.google.gms:google-services", version.ref = "google-play-services" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "google-crashlytics" }
keeper-gradle = { module = "com.slack.keeper:keeper", version.ref = "gradle-keeper" }
firebase-performacne-gralde = { module = "com.google.firebase:perf-plugin", version.ref = "google-performance" }
karumi-gradle = { module = "com.karumi:shot", version.ref = "gradle-karumi" }
animationdisabler-gradle = { module = "pl.droidsonroids.gradle:plugin", version.ref = "gradle-animationdisabler" }
agp-tools-core = { module = "com.android.tools:common", version.ref = "google-tools" }

androidtest-core = { module = "androidx.test:core-ktx", version.ref = "google-androidtest" }
androidtest-runner = { module = "androidx.test:runner", version.ref = "google-androidtest" }
androidtest-rules = { module = "androidx.test:rules", version.ref = "google-androidtest" }
androidtest-junitext = { module = "androidx.test.ext:junit-ktx", version.ref = "google-androidtestext" }
androidtest-coretesting = { module = "androidx.arch.core:core-testing", version.ref = "google-androidArchCore" }

espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "google-espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "google-espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "google-espresso" }
espresso-accessibility = { module = "androidx.test.espresso:espresso-accessibility", version.ref = "google-espresso" }
espresso-idlingresource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "google-espresso" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "mavencentral-junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "mavencentral-junit" }

[plugins]
osacky-gradledoctor = { id = "com.osacky.doctor", version.ref = "gradle-gradledoctor" }
starter-easylauncher = { id = "com.starter.easylauncher", version.ref = "gradle-easylauncher" }
jmailen-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "gradle-kotlinter" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "mavencentral-kotlin" }

[bundles]
espresso = [
    "androidtest-junitext",
    "androidtest-core",
    "androidtest-rules",
    "androidtest-coretesting",
    "espresso-core",
    "espresso-contrib",
    "espresso-intents",
    "espresso-accessibility",
    "espresso-idlingresource",
]
