name: Google Play Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew assembleRelease bundleRelease -PuploadMapping=true
        env:
          WYKOP_KEYSTORE_KEY_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_KEY_PASSWORD }}
          WYKOP_KEYSTORE_KEY_NAME: ${{ secrets.WYKOP_KEYSTORE_KEY_NAME }}
          WYKOP_KEYSTORE_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_PASSWORD }}
          WYKOP_APPKEY: ${{ secrets.WYKOP_APPKEY }}
          WYKOP_SECRETKEY: ${{ secrets.WYKOP_SECRETKEY }}
          WYKOP_GOOGLEKEY: ${{ secrets.WYKOP_GOOGLEKEY }}
          WYKOP_YOUTUBEKEY: ${{ secrets.WYKOP_YOUTUBEKEY }}

      #      - uses: r0adkll/upload-google-play@v1.0.17
      #        with:
      #          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICES_JSON }}
      #          packageName: io.github.wykopmobilny
      #          releaseFiles: app/build/outputs/bundle/release/*.aab
      #          track: internal
      #          mappingFile: app/build/outputs/mapping/release/mapping.txt

      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/release/*.apk

      - uses: softprops/action-gh-release@v0.1.14
        with:
          files: app/build/outputs/apk/release/*.apk

      - uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "service-account.json"
          encodedString: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "otwarty-wykop-mobilny"
          serviceCredentialsFile: service-account.json
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk
