name: Google Play Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        env:
          WYKOP_KEYSTORE_KEY_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_KEY_PASSWORD }}
          WYKOP_KEYSTORE_KEY_NAME: ${{ secrets.WYKOP_KEYSTORE_KEY_NAME }}
          WYKOP_KEYSTORE_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_PASSWORD }}
          WYKOP_APPKEY: ${{ secrets.WYKOP_APPKEY }}
          WYKOP_SECRETKEY: ${{ secrets.WYKOP_SECRETKEY }}
          WYKOP_GOOGLEKEY: ${{ secrets.WYKOP_GOOGLEKEY }}
        with:
          arguments: assembleRelease bundleRelease -PuploadMapping=true

      - uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICES_JSON }}
          packageName: io.github.wykopmobilny
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
          mappingFile: app/build/outputs/mapping/release/mapping.txt

      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/release/*.apk

      - uses: softprops/action-gh-release@v0.1.14
        with:
          files: app/build/outputs/apk/release/*.apk
