name: Build project

on:
  pull_request:

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Code style check
        uses: gradle/gradle-build-action@v1
        with:
          arguments: projectCodestyle
          dependencies-cache-enabled: true

      - name: Assemble
        uses: gradle/gradle-build-action@v1
        env:
          WYKOP_KEYSTORE_KEY_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_KEY_PASSWORD }}
          WYKOP_KEYSTORE_KEY_NAME: ${{ secrets.WYKOP_KEYSTORE_KEY_NAME }}
          WYKOP_KEYSTORE_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_PASSWORD }}
          WYKOP_APPKEY: ${{ secrets.WYKOP_APPKEY }}
          WYKOP_SECRETKEY: ${{ secrets.WYKOP_SECRETKEY }}
          WYKOP_GOOGLEKEY: ${{ secrets.WYKOP_GOOGLEKEY }}
        with:
          arguments: assembleRelease
          dependencies-cache-enabled: true

      - name: Unit tests
        uses: gradle/gradle-build-action@v1
        with:
          arguments: projectCoverage
          dependencies-cache-enabled: true

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Android Lint
        run: ./gradlew projectLint

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: lint-results
          path: '${{ github.workspace }}/**/build/**/reports/lint-results-*.html'

  ui_test:
    runs-on: macos-latest
    env:
      WYKOP_KEYSTORE_KEY_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_KEY_PASSWORD }}
      WYKOP_KEYSTORE_KEY_NAME: ${{ secrets.WYKOP_KEYSTORE_KEY_NAME }}
      WYKOP_KEYSTORE_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_PASSWORD }}
      WYKOP_APPKEY: ${{ secrets.WYKOP_APPKEY }}
      WYKOP_SECRETKEY: ${{ secrets.WYKOP_SECRETKEY }}
      WYKOP_GOOGLEKEY: ${{ secrets.WYKOP_GOOGLEKEY }}
    strategy:
      fail-fast: false
      matrix:
        apiVersion: [ 25, 28 ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: compile ui tests
        uses: gradle/gradle-build-action@v1
        with:
          arguments: app:assembleReleaseTestAndroidTest -PtestBuildType=releaseTest
          dependencies-cache-enabled: true

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.apiVersion }}
          profile: pixel_xl
          target: google_apis
          arch: x86_64
          disable-spellchecker: true
          script: ./gradlew app:connectedReleaseTestAndroidTest -PtestBuildType=releaseTest

      - name: Upload ui tests result
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: uitests-report
          path: "${{ github.workspace }}/**/build/**/connected/"

  screenshot_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: compile screenshot tests
        uses: gradle/gradle-build-action@v1
        with:
          arguments: assembleDebugAndroidTest
          dependencies-cache-enabled: true

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          profile: pixel_xl
          target: google_apis
          arch: x86_64
          disable-spellchecker: true
          script: ./gradlew executeScreenshotTests

      - name: Upload ui tests result
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: screenshots-report
          path: "${{ github.workspace }}/**/build/**/shot/"
