name: Build project

on:
  pull_request:

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Code style check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: projectCodestyle

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        env:
          WYKOP_KEYSTORE_KEY_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_KEY_PASSWORD }}
          WYKOP_KEYSTORE_KEY_NAME: ${{ secrets.WYKOP_KEYSTORE_KEY_NAME }}
          WYKOP_KEYSTORE_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_PASSWORD }}
          WYKOP_APPKEY: ${{ secrets.WYKOP_APPKEY }}
          WYKOP_SECRETKEY: ${{ secrets.WYKOP_SECRETKEY }}
          WYKOP_GOOGLEKEY: ${{ secrets.WYKOP_GOOGLEKEY }}
        with:
          arguments: assembleRelease

      - name: Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: projectCoverage

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Android Lint
        run: ./gradlew projectLint

      - run: ./gradlew verifySqlDelightMigration

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: lint-results
          path: '${{ github.workspace }}/**/build/**/reports/lint-results-*.html'

  ui_test:
    runs-on: macos-latest
    env:
      WYKOP_KEYSTORE_KEY_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_KEY_PASSWORD }}
      WYKOP_KEYSTORE_KEY_NAME: ${{ secrets.WYKOP_KEYSTORE_KEY_NAME }}
      WYKOP_KEYSTORE_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_PASSWORD }}
      WYKOP_APPKEY: ${{ secrets.WYKOP_APPKEY }}
      WYKOP_SECRETKEY: ${{ secrets.WYKOP_SECRETKEY }}
      WYKOP_GOOGLEKEY: ${{ secrets.WYKOP_GOOGLEKEY }}
    strategy:
      fail-fast: false
      matrix:
        apiVersion: [ 25, 28, 30, 31 ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: compile ui tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: app:assembleReleaseTestAndroidTest -PtestBuildType=releaseTest

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.apiVersion }}
          profile: pixel_xl
          target: google_apis
          arch: x86_64
          disable-spellchecker: true
          script: |
            adb logcat -c
            touch app/build/emulator.log
            chmod 777 app/build/emulator.log
            adb logcat >> app/build/emulator.log &
            ./gradlew app:connectedReleaseTestAndroidTest -PtestBuildType=releaseTest

      - name: Upload ui tests result
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: uitests-report${{ matrix.apiVersion }}
          path: "${{ github.workspace }}/**/build/**/connected/"

      - name: Save logcat output
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logcat${{ matrix.apiVersion }}
          path: app/build/emulator.log

  screenshot_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: compile screenshot tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebugAndroidTest

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          profile: pixel_xl
          target: google_apis
          arch: x86
          disable-spellchecker: true
          script: |
            adb shell settings put global hidden_api_policy_p_apps 1
            adb shell settings put global hidden_api_policy_pre_p_apps 1
            adb shell settings put global hidden_api_policy 1
            ./gradlew executeScreenshotTests

      - name: Upload ui tests result
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshots-report
          path: "${{ github.workspace }}/**/build/**/shot/"
